'use client';
import { configureStore } from '@reduxjs/toolkit';
import { rootReducer } from './root-reducer';
import { djangoApi } from './rtk-query/django-api-query';

export const store = () =>
    configureStore({
        // Setup Root reducer which combines all the slices
        reducer: rootReducer,
        // Define the extra middlewares used
        // *DjangoApi middleware auto generated by rtk query should be stated here
        middleware: (getDefaultMiddleware) =>
            getDefaultMiddleware().concat(djangoApi.middleware),
    });

/*
The following types are exported for ease of usage in the entire project
1. RootState is the type of the store
2. AppDispatch is the type for dispatch function for the store
*/

export type AppStore = ReturnType<typeof store>;
export type RootState = ReturnType<AppStore['getState']>;
export type AppDispatch = AppStore['dispatch'];
